# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_post_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='email',
        ),
    ]
