# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20170907_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='owner',
        ),
    ]
